version: '3.3'

services:

  mysql_server:

    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database
    environment:
      - MYSQL_ROOT_PASSWORD=<secret>

  adminer:
  
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_server

  neo4j_server:

    image: neo4j:5.15.0-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    networks:
      - database
    environment:
      - NEO4J_AUTH=none


volumes:

  mysql_data:

    driver: local
    driver_opts:
      type: none
      device: /media/dave/mysql
      o: bind

  neo4j_data:

    driver: local
    driver_opts:
      type: none
      device: /media/dave/neo4j
      o: bind


networks:

  database:
    external: True
